config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'

  resources :users

  resources :actionpoints

  resources :activities

  resources :contactpersoons

  resources :schools

end

app/models/actionpoint.rb
class Actionpoint < ActiveRecord::Base
end

app/controllers/actionpoints_controller.rb
class ActionpointsController < ApplicationController
  before_action :set_actionpoint, only: [:show, :edit, :update, :destroy]

  # GET /actionpoints
  # GET /actionpoints.json
  def index
    @actionpoints = Actionpoint.all
  end

  # GET /actionpoints/1
  # GET /actionpoints/1.json
  def show
  end

  # GET /actionpoints/new
  def new
    @actionpoint = Actionpoint.new
  end

  # GET /actionpoints/1/edit
  def edit
  end

  # POST /actionpoints
  # POST /actionpoints.json
  def create
    @actionpoint = Actionpoint.new(actionpoint_params)

    respond_to do |format|
      if @actionpoint.save
        format.html { redirect_to @actionpoint, notice: 'Actionpoint was successfully created.' }
        format.json { render :show, status: :created, location: @actionpoint }
      else
        format.html { render :new }
        format.json { render json: @actionpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actionpoints/1
  # PATCH/PUT /actionpoints/1.json
  def update
    respond_to do |format|
      if @actionpoint.update(actionpoint_params)
        format.html { redirect_to @actionpoint, notice: 'Actionpoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @actionpoint }
      else
        format.html { render :edit }
        format.json { render json: @actionpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actionpoints/1
  # DELETE /actionpoints/1.json
  def destroy
    @actionpoint.destroy
    respond_to do |format|
      format.html { redirect_to actionpoints_url, notice: 'Actionpoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actionpoint
      @actionpoint = Actionpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actionpoint_params
      params.require(:actionpoint).permit(:action, :status, :datum)
    end
end

app/helpers/actionpoints_helper.rb
module ActionpointsHelper
end

app/views/actionpoints/_form.html.erb
<%= form_for(@actionpoint) do |f| %>
  <% if @actionpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actionpoint.errors.count, "error") %> prohibited this actionpoint from being saved:</h2>

      <ul>
      <% @actionpoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :datum %><br>
    <%= f.date_select :datum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actionpoints/edit.html.erb
<h1>Editing actionpoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @actionpoint %> |
<%= link_to 'Back', actionpoints_path %>

app/views/actionpoints/index.html.erb
<h1>Listing actionpoints</h1>

<table>
  <thead>
    <tr>
      <th>Action</th>
      <th>Status</th>
      <th>Datum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actionpoints.each do |actionpoint| %>
      <tr>
        <td><%= actionpoint.action %></td>
        <td><%= actionpoint.status %></td>
        <td><%= actionpoint.datum %></td>
        <td><%= link_to 'Show', actionpoint %></td>
        <td><%= link_to 'Edit', edit_actionpoint_path(actionpoint) %></td>
        <td><%= link_to 'Destroy', actionpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actionpoint', new_actionpoint_path %>

app/views/actionpoints/new.html.erb
<h1>New actionpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', actionpoints_path %>

app/views/actionpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @actionpoint.action %>
</p>

<p>
  <strong>Status:</strong>
  <%= @actionpoint.status %>
</p>

<p>
  <strong>Datum:</strong>
  <%= @actionpoint.datum %>
</p>

<%= link_to 'Edit', edit_actionpoint_path(@actionpoint) %> |
<%= link_to 'Back', actionpoints_path %>