config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'

  resources :users

  resources :actionpoints

  resources :activities

  resources :contactpersoons

  resources :schools

end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, :address, :postcode, :town, :telephone, presence: true


  # def website=(website)
  #   write_attribute(:website, name.capitalize)
  # end
  #
  # def website
  #   read_attribute(:website)capitalize  # No test for nil?
  # end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.order(:name)
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)
    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :address, :postcode, :town, :telephone, :website, :note, :email)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
    <% if @school.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

          <ul>
            <% @school.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :address %>
      <br>
      <%= f.text_area :address %>
    </div>
    <div class="field">
      <%= f.label :postcode %>
      <br>
      <%= f.text_field :postcode %>
    </div>
    <div class="field">
      <%= f.label :town %>
      <br>
      <%= f.text_field :town %>
    </div>
    <div class="field">
      <%= f.label :telephone %>
      <br>
      <%= f.text_field :telephone %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :website %>
      <br>
      <%= f.text_field :website %>
    </div>
    <div class="field">
      <%= f.label :note %>
      <br>
      <%= f.text_area :note, rows: 6 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Schools</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Naam school</th>
      <th>Adres</th>
      <th>Postcode</th>
      <th>Plaats</th>
      <th>Telefoon</th>
      <th>Email</th>
      <th>Website</th>
      <th>Opmerkingen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.address %></td>
        <td><%= school.postcode %></td>
        <td><%= school.town %></td>
        <td><%= school.telephone %></td>
        <td><%= school.email %></td>
        <td><%= link_to school.website, school.website %></td>
        <td><%= school.note %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-primary">
        <div class="panel-heading"><%= @school.name %></div>
        <div class="panel-body">
            <%= @school.address %><br />
            <%= @school.postcode %> <%= @school.town %><br />
            <%= @school.telephone %><br />
            <%= @school.email %><br />
            <%= link_to "www.albertschweitzer.nl", @school.website %>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">Contactpersoon</div>
        <div class="panel-body">
          <ul>
            <li>Erik Pragt</li>
            <li>06-12345678</li>
            <li>erik@albertschweitzer.nl</li>
          </ul>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">Locatie</div>
        <div class="panel-body">
            <img src="http://www.mappery.com/maps/Bielefeld-Street-Map.mediumthumb.jpg" width="230px">
        </div>
      </div>
    </div>
    <div class="col-md-9">



    <p id="notice"><%= notice %></p>

<p>
  <strong>Naam school:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @school.address %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @school.postcode %>
</p>

<p>
  <strong>Plaats:</strong>
  <%= @school.town %>
</p>

<p>
  <strong>Telefoon:</strong>
  <%= @school.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @school.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= link_to @school.website %>
</p>

<p>
  <strong>Opmerkingen:</strong>
  <%= @school.note %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>


    </div>
  </div>
</div>